services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build: ./user-service
    ports:
      - "4001:5001"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo

  auth-service:
    build: ./auth-service
    ports:
      - "4002:5002"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo

  product-service:
    build: ./product-service
    ports:
      - "4003:5003"
    env_file:
      - ./product-service/.env
    depends_on:
      - mongo

  category-service:
    build: ./category-service
    ports:
      - "4004:5004"
    env_file:
      - ./category-service/.env
    depends_on:
      - mongo

  cart-service:
    build: ./cart-service
    ports:
      - "4005:5005"
    env_file:
      - ./cart-service/.env
    depends_on:
      - mongo
      - product-service

  order-service:
    build: ./order-service
    ports:
      - "4006:5006"
    env_file:
      - ./order-service/.env
    depends_on:
      - mongo
      - cart-service
      - user-service

  payment-service:
    build: ./payment-service
    ports:
      - "4007:5007"
    env_file:
      - ./payment-service/.env
    depends_on:
      - mongo
      - order-service

  notification-service:
    build: ./notification-service
    ports:
      - "4008:5008"
    env_file:
      - ./notification-service/.env
    depends_on:
      - mongo
      - user-service

  lumora-api-gateway:
    build: ./lumora-api-gateway
    container_name: lumora-api-gateway
    ports:
      - "4000:4000"
    volumes:
      - ./lumora-api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./lumora-api-gateway/.env
    depends_on:
      - user-service
      - auth-service
      - product-service
      - category-service
      - cart-service
      - order-service
      - payment-service
      - notification-service

volumes:
  mongo-data:
