apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg==  # base64 for 'mongoadmin'
  MONGO_INITDB_ROOT_PASSWORD: c2VjdXJlcGFzcw==  # base64 for 'securepass'
